<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

use Illuminate\Support\Facades\DB;
use App\Models\Comment;
use Illuminate\Support\Str;

class CommentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('comments')->insert([
            [
                'name'=>'Gramos Shala',
                'comment'=>'Thank you. Very useful.',
                'user_id'=> '7',
                'streaming_id'=>'1',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Gramos Shala',
                'comment'=>'Can t wait - this course looks cool :) thank you again',
                'user_id'=>'7',
                'streaming_id'=>'2',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Almir Pinduk',
                'comment'=>'Can t wait - this course looks cool :) thank you again',
                'user_id'=>'4',
                'streaming_id'=>'1',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Albina Ahmeti',
                'comment'=>'Hi, can you have next course for advance CSS?',
                'user_id'=>'3',
                'streaming_id'=>'1',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Ardit Shaqiri',
                'comment'=>'Hi, I love your lecture on Tailwind CSS.',
                'user_id'=> '5',
                'streaming_id'=>'2',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Blenard Hasani',
                'comment'=>'Can t wait - this course looks cool :) thank you again',
                'user_id'=>'6',
                'streaming_id'=>'2',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Granit Salihu',
                'comment'=>'Hi, I love your lecture on Tailwind CSS.',
                'user_id'=> '8',
                'streaming_id'=>'3',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Gramos Shala',
                'comment'=>'Hi, I love your lecture on Tailwind CSS.',
                'user_id'=> '7',
                'streaming_id'=>'4',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Gramos Shala',
                'comment'=>'Can t wait - this course looks cool :) thank you again',
                'user_id'=>'7',
                'streaming_id'=>'3',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Almir Pinduk',
                'comment'=>'Can t wait - this course looks cool :) thank you again',
                'user_id'=>'4',
                'streaming_id'=>'5',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Albina Ahmeti',
                'comment'=>'Can t wait - this course looks cool :) thank you again',
                'user_id'=>'3',
                'streaming_id'=>'5',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Ardit Shaqiri',
                'comment'=>'Hi, I love your lecture on Tailwind CSS.',
                'user_id'=> '5',
                'streaming_id'=>'4',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Blenard Hasani',
                'comment'=>'Can t wait - this course looks cool :) thank you again',
                'user_id'=>'6',
                'streaming_id'=>'6',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Granit Salihu',
                'comment'=>'Hi, I love your lecture on Tailwind CSS.',
                'user_id'=> '8',
                'streaming_id'=>'6',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Gramos Shala',
                'comment'=>'Hi, I love your lecture on Tailwind CSS.',
                'user_id'=> '7',
                'streaming_id'=>'7',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Gramos Shala',
                'comment'=>'Can t wait - this course looks cool :) thank you again',
                'user_id'=>'7',
                'streaming_id'=>'8',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Almir Pinduk',
                'comment'=>'Can t wait - this course looks cool :) thank you again',
                'user_id'=>'4',
                'streaming_id'=>'8',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Albina Ahmeti',
                'comment'=>'Can t wait - this course looks cool :) thank you again',
                'user_id'=>'3',
                'streaming_id'=>'9',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Ardit Shaqiri',
                'comment'=>'Hi, I love your lecture on Tailwind CSS.',
                'user_id'=> '5',
                'streaming_id'=>'9',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Blenard Hasani',
                'comment'=>'Can t wait - this course looks cool :) thank you again',
                'user_id'=>'6',
                'streaming_id'=>'9',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Granit Salihu',
                'comment'=>'Hi, I love your lecture on Tailwind CSS.',
                'user_id'=> '8',
                'streaming_id'=>'10',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Gramos Shala',
                'comment'=>'Hi, I love your lecture on Tailwind CSS.',
                'user_id'=> '7',
                'streaming_id'=>'11',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Gramos Shala',
                'comment'=>'Can t wait - this course looks cool :) thank you again',
                'user_id'=>'7',
                'streaming_id'=>'12',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Almir Pinduk',
                'comment'=>'Can t wait - this course looks cool :) thank you again',
                'user_id'=>'4',
                'streaming_id'=>'13',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Albina Ahmeti',
                'comment'=>'Can t wait - this course looks cool :) thank you again',
                'user_id'=>'3',
                'streaming_id'=>'14',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Ardit Shaqiri',
                'comment'=>'Hi, I love your lecture on Tailwind CSS.',
                'user_id'=> '5',
                'streaming_id'=>'15',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Blenard Hasani',
                'comment'=>'Can t wait - this course looks cool :) thank you again',
                'user_id'=>'6',
                'streaming_id'=>'16',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Granit Salihu',
                'comment'=>'Hi, I love your lecture on Tailwind CSS.',
                'user_id'=> '8',
                'streaming_id'=>'17',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Gramos Shala',
                'comment'=>'Hi, I love your lecture on Tailwind CSS.',
                'user_id'=> '7',
                'streaming_id'=>'18',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Almir Pinduk',
                'comment'=>'Can t wait - this course looks cool :) thank you again',
                'user_id'=>'4',
                'streaming_id'=>'19',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Albina Ahmeti',
                'comment'=>'Can t wait - this course looks cool :) thank you again',
                'user_id'=>'3',
                'streaming_id'=>'20',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Ardit Shaqiri',
                'comment'=>'Hi, I love your lecture on Tailwind CSS.',
                'user_id'=> '5',
                'streaming_id'=>'21',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Blenard Hasani',
                'comment'=>'Can t wait - this course looks cool :) thank you again',
                'user_id'=>'6',
                'streaming_id'=>'22',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Granit Salihu',
                'comment'=>'Hi, I love your lecture on Tailwind CSS.',
                'user_id'=> '8',
                'streaming_id'=>'23',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Gramos Shala',
                'comment'=>'Hi, I love your lecture on Tailwind CSS.',
                'user_id'=> '7',
                'streaming_id'=>'18',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Almir Pinduk',
                'comment'=>'Can t wait - this course looks cool :) thank you again',
                'user_id'=>'4',
                'streaming_id'=>'19',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Albina Ahmeti',
                'comment'=>'Can t wait - this course looks cool :) thank you again',
                'user_id'=>'3',
                'streaming_id'=>'20',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Ardit Shaqiri',
                'comment'=>'Hi, I love your lecture on Tailwind CSS.',
                'user_id'=> '5',
                'streaming_id'=>'21',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Blenard Hasani',
                'comment'=>'Can t wait - this course looks cool :) thank you again',
                'user_id'=>'6',
                'streaming_id'=>'22',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Granit Salihu',
                'comment'=>'Hi, I love your lecture on Tailwind CSS.',
                'user_id'=> '8',
                'streaming_id'=>'23',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Gramos Shala',
                'comment'=>'Hi, I love your lecture on Tailwind CSS.',
                'user_id'=> '7',
                'streaming_id'=>'24',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Almir Pinduk',
                'comment'=>'Can t wait - this course looks cool :) thank you again',
                'user_id'=>'4',
                'streaming_id'=>'25',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Albina Ahmeti',
                'comment'=>'Can t wait - this course looks cool :) thank you again',
                'user_id'=>'3',
                'streaming_id'=>'26',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Ardit Shaqiri',
                'comment'=>'Hi, I love your lecture on Tailwind CSS.',
                'user_id'=> '5',
                'streaming_id'=>'27',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Blenard Hasani',
                'comment'=>'Can t wait - this course looks cool :) thank you again',
                'user_id'=>'6',
                'streaming_id'=>'28',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Granit Salihu',
                'comment'=>'Hi, I love your lecture on Tailwind CSS.',
                'user_id'=> '8',
                'streaming_id'=>'29',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Gramos Shala',
                'comment'=>'Hi, I love your lecture on Tailwind CSS.',
                'user_id'=> '7',
                'streaming_id'=>'30',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Almir Pinduk',
                'comment'=>'Can t wait - this course looks cool :) thank you again',
                'user_id'=>'4',
                'streaming_id'=>'31',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Albina Ahmeti',
                'comment'=>'Can t wait - this course looks cool :) thank you again',
                'user_id'=>'3',
                'streaming_id'=>'32',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Ardit Shaqiri',
                'comment'=>'Hi, I love your lecture on Tailwind CSS.',
                'user_id'=> '5',
                'streaming_id'=>'33',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Blenard Hasani',
                'comment'=>'Can t wait - this course looks cool :) thank you again',
                'user_id'=>'6',
                'streaming_id'=>'34',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Granit Salihu',
                'comment'=>'Hi, I love your lecture on Tailwind CSS.',
                'user_id'=> '8',
                'streaming_id'=>'35',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Gramos Shala',
                'comment'=>'Hi, I love your lecture on Tailwind CSS.',
                'user_id'=> '7',
                'streaming_id'=>'36',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Almir Pinduk',
                'comment'=>'Can t wait - this course looks cool :) thank you again',
                'user_id'=>'4',
                'streaming_id'=>'37',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Albina Ahmeti',
                'comment'=>'Can t wait - this course looks cool :) thank you again',
                'user_id'=>'3',
                'streaming_id'=>'38',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Ardit Shaqiri',
                'comment'=>'Hi, I love your lecture on Tailwind CSS.',
                'user_id'=> '5',
                'streaming_id'=>'39',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Blenard Hasani',
                'comment'=>'Can t wait - this course looks cool :) thank you again',
                'user_id'=>'6',
                'streaming_id'=>'40',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Granit Salihu',
                'comment'=>'Hi, I love your lecture on Tailwind CSS.',
                'user_id'=> '8',
                'streaming_id'=>'41',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Gramos Shala',
                'comment'=>'Hi, I love your lecture on Tailwind CSS.',
                'user_id'=> '7',
                'streaming_id'=>'42',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Almir Pinduk',
                'comment'=>'Can t wait - this course looks cool :) thank you again',
                'user_id'=>'4',
                'streaming_id'=>'43',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Albina Ahmeti',
                'comment'=>'Can t wait - this course looks cool :) thank you again',
                'user_id'=>'3',
                'streaming_id'=>'44',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Ardit Shaqiri',
                'comment'=>'Hi, I love your lecture on Tailwind CSS.',
                'user_id'=> '5',
                'streaming_id'=>'45',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Blenard Hasani',
                'comment'=>'Can t wait - this course looks cool :) thank you again',
                'user_id'=>'6',
                'streaming_id'=>'46',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Granit Salihu',
                'comment'=>'Hi, I love your lecture on Tailwind CSS.',
                'user_id'=> '8',
                'streaming_id'=>'47',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Gramos Shala',
                'comment'=>'Hi, I love your lecture on Tailwind CSS.',
                'user_id'=> '7',
                'streaming_id'=>'48',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Almir Pinduk',
                'comment'=>'Can t wait - this course looks cool :) thank you again',
                'user_id'=>'4',
                'streaming_id'=>'49',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Albina Ahmeti',
                'comment'=>'Can t wait - this course looks cool :) thank you again',
                'user_id'=>'3',
                'streaming_id'=>'50',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Ardit Shaqiri',
                'comment'=>'Hi, I love your lecture on Tailwind CSS.',
                'user_id'=> '5',
                'streaming_id'=>'51',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Blenard Hasani',
                'comment'=>'Can t wait - this course looks cool :) thank you again',
                'user_id'=>'6',
                'streaming_id'=>'52',
                'created_at'=>'2022-10-11 09:41:46',
            ],
            [
                'name'=>'Granit Salihu',
                'comment'=>'Hi, I love your lecture on Tailwind CSS.',
                'user_id'=> '8',
                'streaming_id'=>'53',
                'created_at'=>'2022-10-11 09:41:46',
            ],
        ]);
    }
}
